### ISSUE TITLE
Can bullets themselves rotate to direction I shoot to?

### ISSUE THREAD

**Issue by Macyrate** [jongallant/Unity-Bullet-Hell#7]
![screenshot1.png](https://i.loli.net/2020/05/09/KuN9UmtYlrf1wp4.png)

If I can rotate bullets like below?

![screenshot2.png](https://i.loli.net/2020/05/09/plAht1W6kxaKz9s.png)

Thanks!

**Comment by jongallant** [comment]
Yes.  You will need to set the ProjectileData.Rotation value in order to do this.  I will include this option in a future build.  For now you could do something like:

`node.Item.Rotation = Mathf.Atan2(deltaPosition.y, deltaPosition.x);`

You could add this line of code in ProjectileEmitterAdvanced, after line 328:

```
// Update foreground and outline color data
UpdateProjectileColor(ref node.Item);

// Rotate projectile towards direction 
node.Item.Rotation = Mathf.Atan2(deltaPosition.y, deltaPosition.x);
```

Have your sprite pointing towards the right when you import it.

**Comment by Macyrate** [comment]
Thank you very much!
